import type { PresentationStep } from "./presentationSteps";

export const BYGG_PRESENTATION_STEPS: PresentationStep[] = [
  {
    id: "bygg-intro",
    view: "intro",
    title: "WorkBuddy",
    description: "Kontroll. Spårbarhet. Ansvar.",
    duration: 6000,
  },
  {
    id: "bygg-slide-1",
    view: "incidents",
    title: "Avvikelsen ingen dokumenterade",
    description: "",
    bullets: [
      "Spricka i ställning upptäcks fredag kl 14",
      "Ingen rapport skrivs – \"vi fixar på måndag\"",
      "Olycka lördag. Arbetsmiljöverket kräver dokumentation",
      "WorkBuddy: foto, servertidsstämpel, rapport på 30 sekunder",
      "Beviskedjan finns innan ni lämnat bygget",
    ],
    duration: 14000,
    icon: "🔴",
  },
  {
    id: "bygg-slide-2",
    view: "certificates",
    title: "Certifikatet som redan gått ut",
    description: "",
    bullets: [
      "Kranförare med utgånget certifikat kör hela veckan",
      "Olycka – försäkringsbolaget granskar behörigheter",
      "Platschefen bär personligt ansvar för kontrollen",
      "Automatisk varning 30 dagar före certifikat utgår",
      "Systemet korsrefererar certifikat mot schema",
    ],
    duration: 14000,
    icon: "⚠️",
  },
  {
    id: "bygg-slide-3",
    view: "incidents",
    title: "Varje ändring loggas permanent",
    description: "",
    bullets: [
      "Servertidsstämpel som inte kan redigeras i efterhand",
      "Användar-ID kopplas automatiskt till varje händelse",
      "Före- och efter-värden sparas vid statusändring",
      "Loggar är skrivskyddade – ingen kan radera historik",
      "Juridiskt hållbar dokumentation vid tvist",
    ],
    duration: 14000,
    icon: "🔒",
  },
  {
    id: "bygg-slide-4",
    view: "dashboard",
    title: "Dashboarden visar vad som brinner",
    description: "",
    bullets: [
      "Öppna, kritiska och försenade avvikelser i realtid",
      "Snitt åtgärdstid per avvikelse synlig direkt",
      "Certifikat som utgår inom 30 dagar flaggas",
      "Aktiv personal och bemanning – en överblick",
      "Hela projektet synligt innan första fikarasten",
    ],
    duration: 13000,
    spotlightSelector: "[data-presentation='kpi-cards']",
    icon: "📊",
  },
  {
    id: "bygg-slide-5",
    view: "incidents",
    title: "Exportera bevis på 30 sekunder",
    description: "",
    bullets: [
      "PDF med foton, tidsstämplar och ansvariga",
      "Redo för Arbetsmiljöverket eller försäkringsbolag",
      "Hela beviskedjan i ett dokument",
      "Varje foto låses med servertidsstämpel vid uppladdning",
      "ÄTA-underlag med verifierbar dokumentation",
    ],
    duration: 13000,
    icon: "📄",
  },
  {
    id: "bygg-slide-6",
    view: "camera",
    title: "Foto till färdig rapport direkt",
    description: "",
    bullets: [
      "Ta bild – systemet föreslår kategori automatiskt",
      "Rubrik och allvarlighetsgrad fylls i av AI",
      "Granskning och publicering under 30 sekunder",
      "Ansvarig notifieras direkt – inget tappas bort",
      "Fungerar på svenska, engelska, polska och arabiska",
    ],
    duration: 13000,
    spotlightSelector: "[data-presentation='camera-buttons']",
    icon: "📸",
  },
  {
    id: "bygg-slide-7",
    view: "schedule",
    title: "Schema och checklistor som bevisar sig",
    description: "",
    bullets: [
      "Realtidsschema synligt för hela teamet i mobilen",
      "Checklistmallar skickas automatiskt till rätt personal",
      "Slutförandetid loggas med servertidsstämpel",
      "Aktivera moduler per projekt efter behov",
      "Personalmodul med roller, certifikat och närvaro",
    ],
    duration: 13000,
    icon: "📅",
  },
  {
    id: "bygg-cta",
    view: "cta",
    title: "Vill ni se hur detta fungerar på ert projekt?",
    description: "",
    duration: 0,
  },
];
