import type { PresentationStep } from "./presentationSteps";

export const BYGG_PRESENTATION_STEPS: PresentationStep[] = [
  {
    id: "bygg-intro",
    view: "intro",
    title: "WorkBuddy",
    description: "Kontroll. Spårbarhet. Ansvar.",
    duration: 6000,
  },
  {
    id: "bygg-slide-1",
    view: "incidents",
    title: "Avvikelsen ingen dokumenterade",
    description: "",
    bullets: [
      "Spricka i ställning upptäcks fredag kl 14",
      "Ingen rapport skrivs – \"vi fixar på måndag\"",
      "Olycka lördag. Arbetsmiljöverket kräver dokumentation",
      "WorkBuddy: foto, servertidsstämpel, rapport på 30 sekunder",
      "Beviskedjan finns innan ni lämnat bygget",
    ],
    duration: 14000,
    icon: "🔴",
  },
  {
    id: "bygg-slide-2",
    view: "camera",
    title: "Foto till färdig rapport direkt",
    description: "",
    bullets: [
      "Fotografera skadan – AI föreslår kategori och allvarlighetsgrad",
      "Rubrik, beskrivning och klassificering fylls i automatiskt",
      "Granska, justera om du vill, publicera – under 30 sekunder",
      "Ansvarig notifieras direkt med bild och tidsstämpel",
      "Ingen manuell klassificering – ingen rapportjakt",
    ],
    duration: 14000,
    spotlightSelector: "[data-presentation='camera-buttons']",
    icon: "📸",
  },
  {
    id: "bygg-slide-3",
    view: "incidents",
    title: "Varje ändring loggas permanent",
    description: "",
    bullets: [
      "Servertidsstämpel som inte kan redigeras i efterhand",
      "Användar-ID kopplas automatiskt till varje händelse",
      "Före- och efter-värden sparas vid statusändring",
      "Loggar är skrivskyddade – ingen kan radera historik",
      "Vid tvist: komplett ändringslogg från dag ett",
    ],
    duration: 14000,
    icon: "🔒",
  },
  {
    id: "bygg-slide-4",
    view: "incidents",
    title: "Exportera bevis på 30 sekunder",
    description: "",
    bullets: [
      "PDF med foton, tidsstämplar, ändringslogg och ansvariga",
      "Före- och efter-bilder krävs innan ärende stängs",
      "Redo för Arbetsmiljöverket, försäkringsbolag eller beställare",
      "Varje foto låses med servertidsstämpel vid uppladdning",
      "ÄTA-underlag med verifierbar dokumentation i ett klick",
    ],
    duration: 13000,
    icon: "📄",
  },
  {
    id: "bygg-slide-5",
    view: "camera",
    title: "Alla förstår – oavsett språk",
    description: "",
    bullets: [
      "Arbetsledaren frågar på svenska – svaret är korrekt",
      "Polsk UE-snickare frågar på polska – samma svar, rätt språk",
      "Arabisktalande betongarbetare får instruktioner på arabiska",
      "Missförstånd minskar – olycksrisken sjunker",
      "Alla kan rapportera avvikelser på sitt eget språk",
    ],
    duration: 14000,
    icon: "🌍",
  },
  {
    id: "bygg-slide-6",
    view: "incidents",
    title: "Från avvikelse till ÄTA-underlag",
    description: "",
    bullets: [
      "Avvikelse rapporteras med foto från mobilen",
      "AI klassificerar, ansvarig tilldelas, åtgärd loggas",
      "Före- och efter-bilder dokumenterar hela förloppet",
      "PDF-rapport genereras med komplett beviskedja",
      "Bevisunderlaget håller i rättslig prövning",
    ],
    duration: 14000,
    icon: "⚖️",
  },
  {
    id: "bygg-cta",
    view: "cta",
    title: "Vill ni se hur detta fungerar på ert projekt?",
    description: "",
    duration: 0,
  },
];
